### ISSUE TITLE
Module doesn’t load on CentOS Stream 9

### ISSUE THREAD

**Issue by ThisIsQasim** [KyleGospo/gasket-dkms#5]
The module installs but never loads (nothing in lsmod or /dev/apex_0) on CentOS 9

**Comment by cyqsimon** [comment]
Might be fixed by google/gasket-driver#16, which has been pulled into this repo.

Try updating.

**Comment by ThisIsQasim** [comment]
Yeah that was the issue. I ended up running sed replace on the dkms folder and it worked. Thanks for maintaining this!
